export const nav = ['About', 'Skills', 'Projects', 'Stack', 'Contact']

export const skills = [
  {
    icon: '',
    label: 'Languages',
    color: 'lavender',
    items: ['JavaScript', 'TypeScript', 'Python', 'C++', 'Java'],
  },
  {
    icon: '',
    label: 'Frontend',
    color: 'blue',
    items: ['React.js', 'Next.js', 'HTML5', 'CSS3', 'Tailwind CSS'],
  },
  {
    icon: '',
    label: 'Backend',
    color: 'peach',
    items: ['Node.js', 'Express.js', 'Firebase', 'Prisma', 'MySQL'],
  },
  {
    icon: '',
    label: 'AI / ML',
    color: 'lavender',
    items: ['Pandas', 'NumPy', 'Scikit-learn', 'Data Analysis', 'ML Models'],
  },
  {
    icon: '',
    label: 'Tools',
    color: 'blue',
    items: ['Figma', 'Git', 'VS Code', 'Postman', 'REST APIs'],
  },
  {
    icon: '',
    label: 'Concepts',
    color: 'peach',
    items: ['DSA', 'OOP', 'DBMS', 'Web Dev', 'Data Viz'],
  },
]

export const projects = [
  {
    id: 1,
    icon: '🧩',
    title: 'FormFit — Upload Preparation Studio',
    description: 'A local-first tool that turns confusing upload requirements into a clear checklist, prepares images and PDFs, and verifies the result before submission.',
    tech: ['Next.js', 'TypeScript', 'PDF.js', 'Tesseract.js', 'RAG'],
    features: [
      'Reads format, size, and dimension requirements',
      'Converts and previews images and PDFs locally',
      'OCR for requirements captured in screenshots',
      'Installable app and Chrome/Edge extension',
    ],
    live: 'https://formfit-chi.vercel.app/',
    code: 'https://github.com/pragya238/formfit',
    gradient: 'from-peach-soft to-orange-light',
    accent: '#c44421',
    status: 'live',
  },
  {
    id: 2,
    icon: '💰',
    title: 'Finance Tracker',
    description: 'A calm, pastel finance workspace for tracking income and expenses, understanding monthly cash flow, and keeping a useful quick view of your money.',
    tech: ['React', 'Node.js', 'Express', 'MongoDB', 'PWA'],
    features: [
      'JWT authentication with role-based access',
      'Pastel dashboard with light and dark themes',
      'Cash-flow, savings-rate, and category summaries',
      'Installable Vercel quick view for phone or laptop',
    ],
    live: 'https://finance-track-nu.vercel.app/',
    code: 'https://github.com/pragya238/Finance_Track',
    gradient: 'from-bluesoft-soft to-[#d0e8f5]',
    accent: '#b8d4e8',
    status: 'live',
  },
  {
    id: 4,
    icon: '🌱',
    title: 'Contribly — Your First Contribution',
    description: 'A personalised open-source workspace that helps beginners discover welcoming GitHub issues and turn their first contribution into clear, manageable steps.',
    tech: ['Next.js', 'TypeScript', 'Auth.js', 'Node.js', 'MongoDB'],
    features: [
      'Live GitHub issue discovery with GSoC and LFX targets',
      'GitHub sign-in and personalised skill preferences',
      'Saved issues and progress synced with MongoDB',
      'Guided checklist for your first pull request',
    ],
    live: 'https://contribly-pragya238.vercel.app/',
    code: 'https://github.com/pragya238/contribly',
    gradient: 'from-peach-soft to-lavender-soft',
    accent: '#31745b',
    status: 'live',
  },
  {
    id: 3,
    icon: '🤖',
    title: 'AI / ML Project',
    description: 'A predictive machine learning model solving real-world classification problems through data analysis and feature engineering.',
    tech: ['Python', 'Pandas', 'NumPy', 'Scikit-learn'],
    features: ['Predictive classification model', 'Data preprocessing pipeline', 'Visual insight reporting'],
    live: null,
    code: null,
    gradient: 'from-peach-soft to-[#fde0d0]',
    accent: '#f5cdb8',
    status: 'coming-soon',
  },
]

export const stack = [
  { label: 'React', category: 'Frontend' },
  { label: 'Next.js', category: 'Frontend' },
  { label: 'Tailwind', category: 'Frontend' },
  { label: 'TypeScript', category: 'Language' },
  { label: 'Node.js', category: 'Backend' },
  { label: 'Express', category: 'Backend' },
  { label: 'Prisma', category: 'Backend' },
  { label: 'MySQL', category: 'Database' },
  { label: 'Firebase', category: 'Backend' },
  { label: 'Python', category: 'Language' },
  { label: 'Pandas', category: 'AI/ML' },
  { label: 'NumPy', category: 'AI/ML' },
  { label: 'Scikit-learn', category: 'AI/ML' },
  { label: 'Figma', category: 'Design' },
  { label: 'Git', category: 'Tools' },
  { label: 'Postman', category: 'Tools' },
  { label: 'REST APIs', category: 'Backend' },
  { label: 'Framer Motion', category: 'Frontend' },
]

export const marqueeItems = [
  'React', '✦', 'Next.js', '✦', 'TypeScript', '✦', 'Node.js', '✦',
  'Express', '✦', 'Prisma', '✦', 'MySQL', '✦', 'Firebase', '✦',
  'Python', '✦', 'Pandas', '✦', 'Scikit-learn', '✦', 'Figma', '✦',
  'Tailwind CSS', '✦', 'REST APIs', '✦', 'Git', '✦', 'Data Viz', '✦',
]
